INSERT INTO tb_service
(name, price, size, description)
VALUES('Banho', 35.60, 1, 'Feito por profissionais qualificados e com produtos próprios para animais, são utilizadas toalhas individuais, limpas e esterilizadas para cada animal, com água em temperatura adequada. Os banhos incluem limpeza de ouvidos e corte de unhas, se necessário.'),
('Tosa', 40.00, 1, 'Realizamos tosa geral, higiênica e própria da raça. Todas feitas por profissionais capacitados, buscando sempre garantir o conforto e bem estar do seu amiguinho. Todas as tosas incluem o banho. As tosas podem ser realizadas em cães, gatos, coelhos e porquinhos da Índia.'),
('Tosa Geral', 60.00, 1, 'A tosa geral é indicada especialmente em casos que há acúmulo de nós que não é possível tirar com o desembolo. Feita com máquina própria para animais, a tosa geral ajuda na transpiração do animal, colaborando para seu bem estar'),
('Tosa higiênica', 20.90, 1, 'A tosa higiênica ajuda a manter a saúde do animal por meio da prevenção do acúmulo de sujeiras em seus pelos, e abrange a barriga, região íntima, ânus e sola das patas. Em algumas raças, pode abranger também a região dos olhos e ouvidos'),
('Tosa de raça', 80.90, 1, 'Na tosa de raça é observado os padrões do desenho de cada tosa e aplicada principalmente para algumas raças como: Shih Tzu, Lhasa Apso, Spitz, Cocker, Poodle e Schnauzer. Consulte a tabela completa com todas as raças atendidas no Patinhas.'),
('Meia tosa higiênica', 15.90, 1, 'A meia tosa higiênica abrange apenas a região do ânus e é indicada para casos em que o animal não precisa de tosa higiênica completa'),
('Hidratação', 50.90, 1, 'Indicada para a maioria das raças de cães, principalmente as de pêlos longos e de fácil embaraçamento, é uma forma de manter a pelagem do seu amiguinho sempre bonita e sedosa. O procedimento é feito juntamente com a devida escovação'),
('Tintura de pelagem', 35.90, 1, 'Disponibilizamos o serviço de tintura de pelagem, utilizando produtos específicos para animais, devidamente testados e aprovados e que não fazem mal algum para o seu pet. Consulte as colorações disponíveis na loja'),
('Desembolo de nós', 70.90, 1, 'O desembolo de pelos é o ato de se desfazer os nós que são formados nos animais de pelos longos e é feito utilizando ferramentas e produtos específicos para tal fim. O desembolo somente é válido para os cães que tenham no máximo 30% do corpo com nós, pois mais do que isso além de dificultar o trabalho de retirada dos nós, pode acabar estressando o animal devido ao trabalho ser sempre dolorido'),
('Escovação de dentes', 10.90, 1, 'Além de ajudar no combate ao mau-hálito, a escovação de dentes regular ajuda a evitar formação de placa bacteriana, cáries, tártaro e até gengivite. A escovação é feita com produtos específicos para animais'),
('Limpeza dos ouvidos', 20.00, 1, 'A limpeza dos ouvidos ajuda a prevenir uma série de doenças bastante comuns e que podem provocar complicações. Cães com orelhas maiores, caídas ou com mais pelos precisam de atenção redobrada. O Patinhas realiza o procedimento de limpeza de ouvidos em todos os banhos'),
('Corte das unhas', 10.90, 1, 'As unhas dos cães devem ser aparadas com frequência para que evitar problemas com vasinhos sanguíneos e nervos que existem nas unhas. Elas devem ser cortadas com muito cuidado e necessitam de um tipo de alicate apropriado para isso. O Patinhas realiza o procedimento de corte de unhas em todos os banhos');
